[nxos:show running-config]
exclude_prefix = !Time,!Command

[nxos:show running-config all]
exclude_prefix = !Time,!Command

[nxos:show hardware]
exclude_contains = uptime

#[nxos:show version]
#exclude_contains = uptime,system restarted

#[ios:show running-config]
#exclude_prefix = Building configuration

#[ios:show version]
#exclude_contains = uptime,Last reload